### PR TITLE
Permit Array Arguments to Mass Assignment Matchers

### LINKED ISSUE #20: Support for array of attributes in permit/forbid_mass_assignment_of
What are the group's thoughts on making the same change to `permit/forbid_mass_assignment_of` as the one that was made in #8?

It would be great to get rid of some of the duplication and manual workarounds for models with lots of permitted attributes.

### PR DESCRIPTION
**Pull request by stephendolan**
Add a form of mass assignment matchers that accepts an array of attributes to permit.

This will resolve #20

### CODE REVIEW

**Comment by chrisalley** [comment]
This looks promising. Can we change the API so that `permit_mass_assignment_of` will accept both attributes and arrays of attributes instead of seperate matchers for each? That way, all three of these would work (and we can add nested attributes in the future):

- `permit_mass_assignment_of(:attribute1)`
- `permit_mass_assignment_of([:attribute1])`
- `permit_mass_assignment_of([:attribute1, :attribute2])

**Comment by stephendolan** [comment]
@chrisalley 

I think that consolidating those functions is a good idea, but it would be a "breaking" change since the error messages would change. Currently, `permit_mass_assignment_of` actually does accept an array as an argument.

What are your thoughts on merging this as a separate piece of functionality so that we can introduce a non-breaking minor version update, then consolidating them in the future into a major version update? That major version change could also go ahead and consolidate `permit_action` and `permit_actions` to give a cleaner API to end-users.

Part of this is my selfish desire to use this behavior in my app sooner rather than later, as it is the driving force behind my contribution to your lovely project, though I do believe there is a compelling reason to introduce the behavior to match the `permit_action` and `permit_actions` convention we are already using.

**Comment by chrisalley** [comment]
> I think that consolidating those functions is a good idea, but it would be a "breaking" change since the error messages would change.

Would this actually break anything? We've already tweaked the error messages in the past (post-1.0), such as in #14. According to [semver](https://semver.org), a major version number is required when the public API changes, but error messages aren't part of the public API (documented in the readme).

I hadn't planned on releasing a Pundit Matchers 2.0, instead focusing on an add-only, never-remove strategy to updating the API. You can just use `permit_actions` in all cases now (and ignore `permit_action` if you don't want to use it). That way users should never have to change their existing specs.

**Comment by stephendolan** [comment]
@chrisalley,

I think that approach is perfectly fine! I'll tweak the pull request over the next week and ping you when I'm happy with where it's at.

Thanks for the good discussion!

**Comment by stephendolan** [comment]
@chrisalley ,

I've made the changes we discussed, and this is ready for your review.

**Pull request merged**
